# Generated by Django 4.1.7 on 2023-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='imagen',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
